---

name: templeHelper

Service:
  Temple:
    image: ghcr.io/a-h/templ:latest
    container_name: templeDevBox
    restart: unless-stopped
    working_dir: /app
    volumes:
      - type : bind
        source: ../app
        target: /app
    ports:
      - "8080:80"
